set -euo pipefail

SCALA_BIN_VER="${SCALA_BIN_VER:-2.12}"
KAFKA_CLIENTS_VERSION_DEFAULT_35="${KAFKA_CLIENTS_VERSION_DEFAULT_35:-3.5.2}"
KAFKA_CLIENTS_VERSION_DEFAULT_34="${KAFKA_CLIENTS_VERSION_DEFAULT_34:-3.4.1}"
LZ4_JAVA_VERSION="${LZ4_JAVA_VERSION:-1.8.0}"
SNAPPY_JAVA_VERSION="${SNAPPY_JAVA_VERSION:-1.1.10.5}"
COMMONS_POOL2_VERSION="${COMMONS_POOL2_VERSION:-2.11.1}"

JARS_DIR="${JARS_DIR:-jars}"
BASE_MVN="${BASE_MVN:-https://repo1.maven.org/maven2}"

mkdir -p "$JARS_DIR"

PYSPARK_VER=$(python - <<'PY'
import pyspark
print(pyspark.__version__)
PY
)

if [[ -z "$PYSPARK_VER" ]]; then
  echo "ERROR: Could not detect pyspark version. Is your venv active?" >&2
  exit 1
fi

SPARK_VER="$PYSPARK_VER"
SPARK_MM=${SPARK_VER%.*}   
SPARK_MAJOR=${SPARK_MM%%.*}
SPARK_MINOR=${SPARK_MM##*.}

if [[ "$SPARK_MAJOR" == "3" && "$SPARK_MINOR" == "5" ]]; then
  KAFKA_CLIENTS_VERSION="${KAFKA_CLIENTS_VERSION:-$KAFKA_CLIENTS_VERSION_DEFAULT_35}"
elif [[ "$SPARK_MAJOR" == "3" && "$SPARK_MINOR" == "4" ]]; then
  KAFKA_CLIENTS_VERSION="${KAFKA_CLIENTS_VERSION:-$KAFKA_CLIENTS_VERSION_DEFAULT_34}"
else
  KAFKA_CLIENTS_VERSION="${KAFKA_CLIENTS_VERSION:-$KAFKA_CLIENTS_VERSION_DEFAULT_35}"
fi

SPARK_SQL_KAFKA_PATH="org/apache/spark/spark-sql-kafka-0-10_${SCALA_BIN_VER}/${SPARK_VER}/spark-sql-kafka-0-10_${SCALA_BIN_VER}-${SPARK_VER}.jar"
SPARK_TOKEN_PROVIDER_PATH="org/apache/spark/spark-token-provider-kafka-0-10_${SCALA_BIN_VER}/${SPARK_VER}/spark-token-provider-kafka-0-10_${SCALA_BIN_VER}-${SPARK_VER}.jar"
KAFKA_CLIENTS_PATH="org/apache/kafka/kafka-clients/${KAFKA_CLIENTS_VERSION}/kafka-clients-${KAFKA_CLIENTS_VERSION}.jar"
LZ4_JAVA_PATH="org/lz4/lz4-java/${LZ4_JAVA_VERSION}/lz4-java-${LZ4_JAVA_VERSION}.jar"
SNAPPY_JAVA_PATH="org/xerial/snappy/snappy-java/${SNAPPY_JAVA_VERSION}/snappy-java-${SNAPPY_JAVA_VERSION}.jar"
COMMONS_POOL2_PATH="org/apache/commons/commons-pool2/${COMMONS_POOL2_VERSION}/commons-pool2-${COMMONS_POOL2_VERSION}.jar"

JAR_URLS=(
  "$BASE_MVN/$SPARK_SQL_KAFKA_PATH"
  "$BASE_MVN/$SPARK_TOKEN_PROVIDER_PATH"
  "$BASE_MVN/$KAFKA_CLIENTS_PATH"
  "$BASE_MVN/$LZ4_JAVA_PATH"
  "$BASE_MVN/$SNAPPY_JAVA_PATH"
  "$BASE_MVN/$COMMONS_POOL2_PATH"
)

fetch() {
  local url="$1"; local out="$2"
  echo "-> Fetching $(basename "$out")"
  if command -v curl >/dev/null 2>&1; then
    curl -fL --retry 3 --retry-delay 1 -o "$out" "$url" || return 1
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$out" "$url" || return 1
  else
    echo "ERROR: Neither curl nor wget found" >&2
    return 1
  fi
}

for url in "${JAR_URLS[@]}"; do
  fname=$(basename "$url")
  dest="$JARS_DIR/$fname"
  if [[ -f "$dest" ]]; then
    echo "= Skipping (exists): $dest"
    continue
  fi
  if ! fetch "$url" "$dest"; then
    cat >&2 <<EOF
ERROR: Failed to download
  $url
This is often due to corporate SSL inspection blocking direct downloads from Maven Central.
Workarounds:
  1) Re-run with your internal Maven mirror, e.g.:
       BASE_MVN=https://<corp-nexus>/repository/maven-public/ $0
  2) Manually download the file in a browser and place it at:
       $dest
EOF
    exit 2
  fi
  echo "   saved -> $dest"

done

JAR_LIST=$(ls -1 "$JARS_DIR" | grep -E '^(spark-sql-kafka-0-10_|spark-token-provider-kafka-0-10_|kafka-clients-|lz4-java-|snappy-java-|commons-pool2-).*\.jar$' | sed "s|^|$JARS_DIR/|")
JARS_CSV=$(printf ",%s" $JAR_LIST)
JARS_CSV=${JARS_CSV:1}

cat > .env.pyspark <<ENV
# Auto-generated by scripts/setup_kafka_connectors.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Spark ${SPARK_VER}, Scala ${SCALA_BIN_VER}
export PYSPARK_SUBMIT_ARGS="--jars ${JARS_CSV} pyspark-shell"
ENV

echo
echo " Kafka connector jars ready in '$JARS_DIR'"
echo " Added commons-pool2 ${COMMONS_POOL2_VERSION} (required by Spark Kafka consumer pool)"
echo " Created '.env.pyspark' with PYSPARK_SUBMIT_ARGS"
echo "Next: source the env and run your job, e.g.:"
echo "    source .env.pyspark && python apps/streaming_kafka.py --config configs/stream_config.yml"